### ISSUE TITLE
not getting how it works

### ISSUE THREAD

**Issue by DhansAL** [fasiha/jmdict-simplified-node#1]
I tried using this but I got confused and had a few bugs
1. when do you mention the downloaded `jmdict.JSON.zip` file path in the setup function? 
2. does the setup function gets called after each load of the app?
3. I got type errors on running the package

can you explain the setup with an example function?

**Comment by fasiha** [comment]
Hi @DhansAL thanks for writing! I totally agree with you, the README could definitely use more explanation. I added a Tutorial section to it

https://github.com/fasiha/jmdict-simplified-node#tutorial

to try and address these questions. It echoes the [installation/setup](https://github.com/fasiha/jmdict-simplified-node#installation-and-setup) section in asking you to download JMDict-Simplified's JSON file, and shows how you how to run the `setup` and use its return value.

I also added more details to the README that explain that you only need to call `setup` once in your entire app—to get the `db` value that you pass to the other functions.

I created a fresh Node module with
```bash
mkdir testing-issue-1
cd testing-issue-1
npm init -y
npm i jmdict-simplified-node
npm i -D ts-node
```
then dropped the `demo.ts` from the README's [tutorial section](https://github.com/fasiha/jmdict-simplified-node#tutorial) into here and ran it:
```
npx ts-node demo.ts
```
and the first time it runs, it's setting up the database for fast lookups and will take 1~2 minutes to complete. If you rerun `npx ts-node demo.ts`, it should run instantaneously.

Let me know if this helps!
